OPTION_FOR_KEEPING_SANDBOX_DIRECTORY__LONG = '--keep'
OPTION_FOR_KEEPING_SANDBOX_DIRECTORY__SHORT = '-k'

OPTION_FOR_EXECUTING_ACT_PHASE__LONG = '--act'

OPTION_FOR_PREPROCESSOR__LONG = '--preprocessor'

PREPROCESSOR_OPTION_ARGUMENT = 'PROGRAM'

OPTION_FOR_ACTOR__LONG = '--actor'

ACTOR_OPTION_ARGUMENT = 'PROGRAM'

INTERPRETER_ACTOR_TERM = 'interpreter actor'

TEST_CASE_FILE_ARGUMENT = 'FILE'
