OPTION_FOR_KEEPING_SANDBOX_DIRECTORY__LONG = '--keep'
OPTION_FOR_KEEPING_SANDBOX_DIRECTORY__SHORT = '-k'

OPTION_FOR_EXECUTING_ACT_PHASE__LONG = '--act'

OPTION_FOR_PREPROCESSOR__LONG = '--preprocessor'

OPTION_FOR_ACTOR__LONG = '--actor'
SUITE_COMMAND = 'suite'
