from shellcheck_lib.help.concepts.configuration_parameters.configuration_parameter import \
    EXECUTION_MODE_CONFIGURATION_PARAMETER, HOME_DIRECTORY_CONFIGURATION_PARAMETER

ALL_CONFIGURATION_PARAMETERS = [
    EXECUTION_MODE_CONFIGURATION_PARAMETER,
    HOME_DIRECTORY_CONFIGURATION_PARAMETER,
]
