from exactly_lib.definitions.primitives import program

IDENTITY_TRANSFORMER_NAME = 'identity'
REPLACE_TRANSFORMER_NAME = 'replace'
SELECT_TRANSFORMER_NAME = 'filter'
SEQUENCE_OPERATOR_NAME = '|'
RUN_PROGRAM_TRANSFORMER_NAME = program.RUN_PROGRAM_PRIMITIVE
RUN_WITH_IGNORED_EXIT_CODE_OPTION_NAME = program.WITH_IGNORED_EXIT_CODE_OPTION_NAME
