from exactly_lib.test_case_file_structure.path_relativity import RelHdsOptionType
from exactly_lib_test.test_case_utils.test_resources import relativity_options

PROGRAM_FILE = relativity_options.conf_rel_hds(RelHdsOptionType.REL_HDS_CASE)
INTERPRETER_FILE = relativity_options.conf_rel_hds(RelHdsOptionType.REL_HDS_CASE)
ATC_FILE = relativity_options.conf_rel_hds(RelHdsOptionType.REL_HDS_ACT)
