from exactly_lib.help.utils.section_contents_renderer import RenderingEnvironment
from exactly_lib_test.help.test_resources import CrossReferenceTextConstructorTestImpl

RENDERING_ENVIRONMENT = RenderingEnvironment(CrossReferenceTextConstructorTestImpl())
