CHANGE_DIR_INSTRUCTION_NAME = 'cd'

SHELL_INSTRUCTION_NAME = '$'

EXECUTION_MODE_INSTRUCTION_NAME = 'mode'

HOME_DIRECTORY_INSTRUCTION_NAME = 'home'

ACTOR_INSTRUCTION_NAME = 'actor'

TIMEOUT_INSTRUCTION_NAME = 'timeout'
