from exactly_lib.help_texts.instruction_arguments import NEGATION_ARGUMENT_STR
from exactly_lib.instructions.assert_.utils.file_contents_resources import EMPTINESS_CHECK_ARGUMENT

NOT_ARGUMENT = NEGATION_ARGUMENT_STR
EMPTY_ARGUMENT = EMPTINESS_CHECK_ARGUMENT
EQUALS_ARGUMENT = 'equals'
NUM_LINES_ARGUMENT = 'num-lines'

LINE_ARGUMENT = 'line'
MATCHES_ARGUMENT = 'matches'

ANY_LINE_ARGUMENT = 'any'
EVERY_LINE_ARGUMENT = 'every'

ALL_CHECKS = (
    EQUALS_ARGUMENT,
    EMPTY_ARGUMENT,
    ' '.join([ANY_LINE_ARGUMENT, LINE_ARGUMENT, MATCHES_ARGUMENT]),
    ' '.join([EVERY_LINE_ARGUMENT, LINE_ARGUMENT, MATCHES_ARGUMENT]),
    NUM_LINES_ARGUMENT,
)
