from exactly_lib.help_texts.instruction_arguments import NEGATION_ARGUMENT_STR, EXISTS_QUANTIFIER_ARGUMENT, \
    ALL_QUANTIFIER_ARGUMENT
from exactly_lib.instructions.assert_.utils.file_contents_resources import EMPTINESS_CHECK_ARGUMENT

NOT_ARGUMENT = NEGATION_ARGUMENT_STR
EMPTY_ARGUMENT = EMPTINESS_CHECK_ARGUMENT
EQUALS_ARGUMENT = 'equals'
NUM_LINES_ARGUMENT = 'num-lines'

LINE_ARGUMENT = 'line'
MATCHES_ARGUMENT = 'matches'

ALL_CHECKS = (
    EQUALS_ARGUMENT,
    EMPTY_ARGUMENT,
    ' '.join([EXISTS_QUANTIFIER_ARGUMENT, LINE_ARGUMENT, MATCHES_ARGUMENT]),
    ' '.join([ALL_QUANTIFIER_ARGUMENT, LINE_ARGUMENT, MATCHES_ARGUMENT]),
    NUM_LINES_ARGUMENT,
)

NUM_LINES_DESCRIPTION = 'number of lines'
