from exactly_lib.help_texts import conf_params

TRANSFORM_FILE_INSTRUCTION_NAME = 'transform'

CHANGE_DIR_INSTRUCTION_NAME = 'cd'

SHELL_INSTRUCTION_NAME = '$'

SYMBOL_DEFINITION_INSTRUCTION_NAME = 'def'

CONTENTS_OF_STDOUT_INSTRUCTION_NAME = 'stdout'

EXECUTION_MODE_INSTRUCTION_NAME = conf_params.EXECUTION_MODE

HOME_CASE_DIRECTORY_INSTRUCTION_NAME = conf_params.HOME_CASE_DIRECTORY

HOME_ACT_DIRECTORY_INSTRUCTION_NAME = conf_params.HOME_ACT_DIRECTORY

ACTOR_INSTRUCTION_NAME = conf_params.ACTOR

TIMEOUT_INSTRUCTION_NAME = conf_params.TIMEOUT
