CHANGE_DIR_INSTRUCTION_NAME = 'cd'

SHELL_INSTRUCTION_NAME = '$'

EXECUTION_MODE_INSTRUCTION_NAME = 'mode'

HOME_CASE_DIRECTORY_INSTRUCTION_NAME = 'home'

HOME_ACT_DIRECTORY_INSTRUCTION_NAME = 'act-home'

ACTOR_INSTRUCTION_NAME = 'actor'

TIMEOUT_INSTRUCTION_NAME = 'timeout'

SYMBOL_DEFINITION_INSTRUCTION_NAME = 'def'

CONTENTS_OF_STDOUT_INSTRUCTION_NAME = 'stdout'
