from exactly_lib.help_texts import conf_params

RUN_INSTRUCTION_NAME = 'run'

NEW_FILE_INSTRUCTION_NAME = 'file'

NEW_DIR_INSTRUCTION_NAME = 'dir'

ENV_VAR_INSTRUCTION_NAME = 'env'

CHANGE_DIR_INSTRUCTION_NAME = 'cd'

SHELL_INSTRUCTION_NAME = '$'

SYMBOL_DEFINITION_INSTRUCTION_NAME = 'def'

CONTENTS_OF_STDOUT_INSTRUCTION_NAME = 'stdout'

TEST_CASE_STATUS_INSTRUCTION_NAME = conf_params.TEST_CASE_STATUS

HOME_CASE_DIRECTORY_INSTRUCTION_NAME = conf_params.HOME_CASE_DIRECTORY

HOME_ACT_DIRECTORY_INSTRUCTION_NAME = conf_params.HOME_ACT_DIRECTORY

ACTOR_INSTRUCTION_NAME = conf_params.ACTOR

TIMEOUT_INSTRUCTION_NAME = conf_params.TIMEOUT

FILE_INCLUSION_DIRECTIVE_NAME = 'including'
