PAREN_BEGIN = '('
PAREN_END = ')'

BRACKET_BEGIN = '['
BRACKET_END = ']'

BRACE_BEGIN = '{'
BRACE_END = '}'
BRACE__END__FOR_FORMAT_STRINGS = '}}'

COLON = ':'

RESERVED_TOKENS = (PAREN_BEGIN, PAREN_END, BRACKET_BEGIN, BRACKET_END, BRACE_BEGIN, BRACE_END, COLON)
