from exactly_lib.help.entity_names import CONCEPT_ENTITY_TYPE_NAME, ACTOR_ENTITY_TYPE_NAME, \
    SUITE_REPORTER_ENTITY_TYPE_NAME

HELP = 'help'
INSTRUCTIONS = 'instructions'
TEST_CASE = 'case'
TEST_SUITE = 'suite'
SPECIFICATION = 'spec'
CONCEPT = CONCEPT_ENTITY_TYPE_NAME
ACTOR = ACTOR_ENTITY_TYPE_NAME
SUITE_REPORTER = SUITE_REPORTER_ENTITY_TYPE_NAME
HTML_DOCUMENTATION = 'htmldoc'
