from exactly_lib.symbol.sdv_structure import ReferenceRestrictions
from exactly_lib_test.test_resources.value_assertions.value_assertion import Assertion
from exactly_lib_test.type_val_deps.test_resources.w_str_rend.data_restrictions_assertions import \
    is_reference_restrictions__string__w_all_indirect_refs_are_strings


def is_reference_restrictions__integer_expression() -> Assertion[ReferenceRestrictions]:
    return is_reference_restrictions__string__w_all_indirect_refs_are_strings()
