CONFIGURATION_PHASE_NAME = 'conf'
SETUP_PHASE_NAME = 'setup'
ACT_PHASE_NAME = 'act'
BEFORE_ASSERT_PHASE_NAME = 'before-assert'
ASSERT_PHASE_NAME = 'assert'
CLEANUP_PHASE_NAME = 'cleanup'

SECTION_CONCEPT_NAME = 'phase'
