from exactly_lib.execution.phase_step_identifiers import phase_step

CONFIGURATION__MAIN = phase_step.CONFIGURATION__MAIN.simple

SETUP__VALIDATE_PRE_EDS = phase_step.SETUP__VALIDATE_PRE_EDS.simple
SETUP__VALIDATE_POST_SETUP = phase_step.SETUP__VALIDATE_POST_SETUP.simple
SETUP__MAIN = phase_step.SETUP__MAIN.simple

ALL_SETUP = (SETUP__VALIDATE_PRE_EDS,
             SETUP__VALIDATE_POST_SETUP,
             SETUP__MAIN)

ACT__VALIDATE_PRE_EDS = phase_step.ACT__VALIDATE_PRE_EDS.simple
ACT__VALIDATE_POST_SETUP = phase_step.ACT__VALIDATE_POST_SETUP.simple
ACT__MAIN = phase_step.ACT__MAIN.simple
ACT__PREPARE = phase_step.ACT__PREPARE.simple
ACT__EXECUTE = phase_step.ACT__EXECUTE.simple

ALL_ACT = (ACT__VALIDATE_PRE_EDS,
           ACT__VALIDATE_POST_SETUP,
           ACT__MAIN,
           ACT__PREPARE,
           ACT__EXECUTE)

BEFORE_ASSERT__VALIDATE_PRE_EDS = phase_step.BEFORE_ASSERT__VALIDATE_PRE_EDS.simple
BEFORE_ASSERT__VALIDATE_POST_SETUP = phase_step.BEFORE_ASSERT__VALIDATE_POST_SETUP.simple
BEFORE_ASSERT__MAIN = phase_step.BEFORE_ASSERT__MAIN.simple

ALL_BEFORE_ASSERT = (BEFORE_ASSERT__VALIDATE_PRE_EDS,
                     BEFORE_ASSERT__VALIDATE_POST_SETUP,
                     BEFORE_ASSERT__MAIN)

ASSERT__VALIDATE_PRE_EDS = phase_step.ASSERT__VALIDATE_PRE_EDS.simple
ASSERT__VALIDATE_POST_SETUP = phase_step.ASSERT__VALIDATE_POST_SETUP.simple
ASSERT__MAIN = phase_step.ASSERT__MAIN.simple

ALL_ASSERT = (ASSERT__VALIDATE_PRE_EDS,
              ASSERT__VALIDATE_POST_SETUP,
              ASSERT__MAIN)

CLEANUP__VALIDATE_PRE_EDS = phase_step.CLEANUP__VALIDATE_PRE_EDS.simple
CLEANUP__MAIN = phase_step.CLEANUP__MAIN.simple

ALL_CLEANUP = (CLEANUP__VALIDATE_PRE_EDS,
               CLEANUP__MAIN)
