from exactly_lib.symbol.sdv_structure import ReferenceRestrictions
from exactly_lib_test.test_resources.value_assertions.value_assertion import ValueAssertion
from exactly_lib_test.type_val_deps.data.test_resources.concrete_restriction_assertion import \
    is_string_made_up_of_just_strings_reference_restrictions
from exactly_lib_test.type_val_deps.types.string.test_resources.string import \
    IS_STRING_MADE_UP_OF_JUST_STRINGS_REFERENCE_RESTRICTION


def is_integer_expression_string() -> ValueAssertion[ReferenceRestrictions]:
    return is_string_made_up_of_just_strings_reference_restrictions()


IS_INTEGER_STR_REFERENCE_RESTRICTIONS = IS_STRING_MADE_UP_OF_JUST_STRINGS_REFERENCE_RESTRICTION
