#!/usr/bin/env bash

function exit_error() { # MSG
  echo $(basename $0)": $1" >&2
  exit 1
}

if [ $# -ne 2 ]; then
  exit_error 'TYPE CASE-OR-SUITE-FILE'
fi

type_name=$1
file=$2

if [ ! -f "${file}" ]; then
  exit_error "Not a file: ${file}"
fi

here=$(dirname "$0")
xly="python3 ${here}/../../src/default-main-program-runner.py"

function list_defined_names() {
  ${xly} symbol ${file} | grep ${type_name} | cut -d ' ' -f 3
}

all_defined_names=$(list_defined_names)

for name in $all_defined_names; do
  echo '========================================'
  $xly symbol "${file}" "${name}"
done
